# Generated by Django 4.2.6 on 2024-10-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='menu_fotos/', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='menu',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
