# Generated by Django 4.2.6 on 2024-10-06 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
